name: Go

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o go-touch-mapper_x86
    
    - name: list
      run: ls -al
    - name: help
      run: ./go-touch-mapper_x86 -h

